#!/bin/bash
set -x
export WIPE_DATA="NO"
export DATAjob="${DATAROOT}/${RUN}_dajob.${PDY:-}${cyc}"
export DATAens="${DATAjob}/ensdata"
export DATA="${DATAjob}/coupledanlvar"
source "${HOMEglobal}/ush/jjob_header.sh" -e "coupledanlfinal" -c "base coupledanl coupledanlfinal"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
declare -rx COMIN_OBS="${ROTDIR}/${RUN}.${PDY}/${cyc}/obs"

declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_OCEAN_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ocean"
declare -rx COMOUT_ICE_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ice"
declare -rx COMOUT_ICE_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ice/restart"
declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"

mkdir -m 775 -p "${COMOUT_ATMOS_ANALYSIS}"
mkdir -m 775 -p "${COMOUT_OCEAN_ANALYSIS}"
mkdir -m 775 -p "${COMOUT_ICE_ANALYSIS}"
mkdir -m 775 -p "${COMOUT_CONF}"

###############################################################
# Run relevant script

EXSCRIPT=${GDASCOUPLEDANALYSIS:-${SCRglobal}/exglobal_coupled_analysis_finalize.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to finalize the coupled analysis"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to change directory to ${DATAROOT} to remove temporary data"
fi

if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATAjob}"
fi

exit 0
